server:

    #address: localhost
    #port: 8081
    error:
        include-message: always
        include-binding-errors: always

spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/LMSplatform
        username: postgres
        password: 66c#Abi^Xqjj
jpa:
    hibernate:
        ddl-auto: update
    properties:
        hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
            format_sql: true
    show-sql: true
jwt:
    secret: L7#k@!Xz&9P#HwQ$2gC8*MdN%RtBvY^UzWpE$A@Df&TG$4@J9*KhL
    issuer: lms-platform # Optional, used to validate the token issuer
#    expiration: 36000000 # Token expiration time in milliseconds (10 hours)
